version: '3.9'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: blog
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/blog
      JWT_SECRET: super-secret-key
      JWT_EXPIRES_IN: 1d
      CLIENT_URL: http://localhost:8080
    depends_on:
      - mongo
    ports:
      - '4000:4000'

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '8080:80'

volumes:
  mongo_data:
